# rplidar_composition 노드에 바로 주입됨
rplidar:
  ros__parameters:
    serial_port: /dev/ttyUSB0
    serial_baudrate: 115200
    frame_id: laser
    angle_compensate: true
    scan_mode: Standard   # 장치에 따라 변경 가능
